rvm: 2.1.2
notifications:
  email:
    - false
env:
  - PUPPET_VERSION=3.0.0
  - PUPPET_VERSION=3.1.0
  - PUPPET_VERSION=3.2.0
  - PUPPET_VERSION=3.3.0
  - PUPPET_VERSION=3.4.0
  - PUPPET_VERSION=3.5.0
  - PUPPET_VERSION=3.6.0
  - PUPPET_VERSION=3.7.0
